synonyms:
  低空经济:
    - 低空产业
    - 通用航空
    - 通航
    - eVTOL
    - 航空产业
  规划纲要:
    - 纲要
    - 规划
    - 顶层规划
  国家综合立体交通网:
    - 综合立体交通网
    - 交通网规划
    - 交通运输规划
  无人驾驶航空器:
    - 无人机
    - 民用无人驾驶航空器
    - 无人航空器
